name: build-release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-lin:
    runs-on: ubuntu-latest
    environment: snapshots 
    steps:
    - name: Checkout source
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Upload binaries to snapshots
      run: |
          echo "$NOTES" > notes.txt
          gh release create 33457 -R alexx2000/snapshots -t "Revision 33457" --latest --notes-file README.md *.pp 
      env:
        NOTES: ${{ vars.BODY }}      
        GH_TOKEN: ${{ secrets.SNAPSHOTS }}
