name: build-snapshot3

on:
  workflow_dispatch:
  push:
    paths:
    - 'components/**'
    - 'plugins/**'
    - 'sdk/**'
    - 'src/**'
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mac:
    runs-on: macos-15
    steps:
    - name: Restore fpc from cache
      id: fpc-restore
      uses: actions/cache/restore@v6
      with:
        path: ${{ runner.temp }}/fpc-dmg
        key: ${{ runner.os }}-fpc
    
    - name: Download fpc from site
      if: steps.fpc-restore.outputs.cache-hit != 'true'
      run: |
            curl -L -o "${{ runner.temp }}/fpc.dmg" \
            https://downloads.freepascal.org/fpc/beta/3.2.4-rc2/aarch64-macosx/fpc-3.2.4rc2.intelarm64-macosx.dmg
            hdiutil attach "${{ runner.temp }}/fpc.dmg" -mountpoint "${{ runner.temp }}/fpc-dmg"

    - name: Save fpc to cache
      if: steps.fpc-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v6
      with:
        path: ${{ runner.temp }}/fpc-dmg
        key: ${{ runner.os }}-fpc

    - name: Install Free Pascal
      run: sudo installer -pkg "${{ runner.temp }}/fpc-dmg/fpc-3.2.4rc2-intelarm64-macosx.pkg" -target /
  
    - name: Get Lazarus source
      uses: actions/checkout@v7
      with:
            repository: 'fpc/Lazarus'

    - name: Build and install Lazarus
      run: |
           make all
           sudo make install

    - name: Create Lazarus config
      run: |
           mkdir -p $HOME/.lazarus
           cp tools/install/macosx/environmentoptions.xml $HOME/.lazarus/environmentoptions.xml
           sed -i -e "s|_PPCARCH_|fpc|g; s|/Developer/lazarus|/usr/local/share/lazarus|g" $HOME/.lazarus/environmentoptions.xml


   
